// Generated by scripts/mine-corrections.ts — do not edit by hand.
// Re-run the script after a stretch of reviewing and commit the diff.
//
// Phrasing the reviewer has replaced at least twice, in different paragraphs,
// mined out of devotional_corrections. This is style, not terminology: single
// terms belong in the glossary (devotional_glossary), where flagParagraph can
// check them; the turn of a sentence belongs here, where the suggester reads it.
//
// Cross-system: BookForge consumes rules separately. This file is the hand-off
// artifact and nothing here reaches ~/Projects/book-system automatically.
//
// Source: 8 corrections, mined 2026-08-30.

export interface MinedRule {
    /** The phrasing the reviewer keeps replacing. */
    from: string;
    /** What he replaces it with. */
    to: string;
    /** How many corrections showed this substitution. */
    hits: number;
    /** In how many distinct paragraphs — the reason it is a rule and not a one-off. */
    paragraphs: number;
}

/** Most-frequent first, so a caller that caps the list keeps the strongest. */
export const MINED_RULES: MinedRule[] = [];
